"""Deleting request table.

Revision ID: ce4842776df2
Revises: 49f49cb14da1
Create Date: 2022-07-14 16:35:57.342615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce4842776df2'
down_revision = '49f49cb14da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestforproduct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestforproduct',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('productId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orderId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requestAmount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['orders.id'], name='requestforproduct_ibfk_1'),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], name='requestforproduct_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
